/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123619-g44ad73031d-20260325"
#endif /* AVUTIL_FFVERSION_H */
